run:
  timeout: 10m

output:
  sort-results: true
  show-stats: true

linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 10
    skip-tests: true
  dupl:
    threshold: 120
  errcheck:
    exclude-functions:
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: true
  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 80
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/rabbitmq/amqp091-go)
      - localmodule
    custom-order: true
  gocognit:
    min-complexity: 20
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - emptyStringTest
      - hugeParam
      - ifElseChain
      - ruleguard
      - sloppyReassign
      - whyNoLint # nolintlint is better
    settings:
      captLocal:
        paramsOnly: false
      unnamedResult:
        checkExported: true
  gofmt:
    simplify: false # covered by gofumpt
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
  govet:
    enable-all: true
    disable:
      - fieldalignment
  grouper:
    import-require-single-import: true
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-functions:
      - strings.SplitN
  nakedret:
    max-func-lines: 50
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: argument-limit
        arguments:
          - 8
      - name: atomic
      - name: bool-literal-in-expr
      - name: confusing-results
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: datarace
      - name: defer
      - name: error-naming
      - name: error-return
        arguments:
          - "preserveScope"
      - name: errorf
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-value-receiver
      - name: optimize-operands-order
      - name: redundant-import-alias
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: var-naming
  stylecheck:
    checks:
      - "all"
      - "-ST1000"
  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    sql-isolation-level: true
    tls-signature-scheme: true
    constant-kind: true
  varnamelen:
    max-distance: 10

linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - interfacebloat
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - revive
    - spancheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace

issues:
  include:
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0006
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - dupl
        - exhaustive
        - exhaustruct
        - forcetypeassert
        - funlen
        - mnd
        - nakedret
        - spancheck
        - varnamelen
  max-issues-per-linter: 0
  max-same-issues: 0
