coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: true
ignore:
  - "mocks/**"
