name: ci
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: latest
  test-coverage:
    name: test-coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'oldstable', 'stable' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Test
        run: gotestsum --junitfile junit.xml --format testname -- -json -coverpkg=./... -coverprofile=./coverage.txt -covermode=atomic ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.4.3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-race:
    name: test-race
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 'oldstable', 'stable' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests with race detector
        run: go test -race ./...
